# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20170913_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
