# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('enquiry', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
    ]
