# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170903_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='postcode',
        ),
    ]
