# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20170902_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='customer_id',
        ),
    ]
